### ISSUE TITLE
Add TypeScript Definition file (index.d.ts)

### ISSUE THREAD

**Issue by blove** [talyssonoc/awilix-express#1]
This looks like a great solution for dependency injection in Express! It would be great if there was a TypeScript definition file (index.d.ts) so that the `container` property on the `Request` interface existed. Otherwise TS developers get an error: `Property 'container' does not exist on type 'Request'`.

**Comment by blove** [comment]
This is related to: https://github.com/jeffijoe/awilix/issues/14

**Comment by blove** [comment]
I have submitted a PR for this issue.

**Comment by talyssonoc** [comment]
Hey, sorry for the delay. This is great, thanks for the contribution! 😄 I'm gonna accept the PR, do you think you could send a PR for add type definitions for `makeInvoker` and `makeClassInvoker` as well? I don't have too much experience with TypeScript yet (I'm planning to study it deeper to add type definitions for my [Structure](https://github.com/talyssonoc/structure/) lib, actually haha).
