### ISSUE TITLE
Scoped logger per request?

### ISSUE THREAD

**Issue by guumaster** [talyssonoc/awilix-express#13]
Is possible to have a scoped logger in a submodule used in the controller?

`controller(scoped)` => `moduleA` => `moduleB`. 

I want to use a `logger` on moduleB scoped to the request (with traceId, correlation, etc). Is it possible?  Thanks

**Comment by jeffijoe** [comment]
Yes it is, you register the preconfigured logger in a middleware that runs before your controller code. I do this for the same reason, contextual logging. 😄

**Comment by jeffijoe** [comment]
Here's an example. Include this before your controllers get resolved, and any module that gets resolved in that scope will receive that logger.

```js
app.use((req, res) => {
  const logger = {
    log: (message) => {
      console.log(`${req.method} ${req.path}: ${message}`)
    }
  }

  req.container.register({
    logger: asValue(logger)
  })
})
```

**Comment by talyssonoc** [comment]
Thank you for the help, @jeffijoe!

**Comment by guumaster** [comment]
This works perfectly. Thanks!
