### ISSUE TITLE
unhandledRejection when returning promises from routes

### ISSUE THREAD

**Issue by sbarry157** [talyssonoc/awilix-express#19]
We would like to start using awilix-express moving forward, but promise rejections are not handled as we expected. Using express-promise-router, our pattern is this:

all routes return promises
When an error happens, throw immediately.
register an error handler (app.use) to inspect the error and return the appropriate response.

I noticed [#15 ](https://github.com/talyssonoc/awilix-express/pull/15) relates to this issue.

But in looking at the code, I see that the error is re-thrown after calling `next`. I think this is causing the issue. 

```javascript
function asyncErrorWrapper(
  fn: (...args: any[]) => any
): (...args: any[]) => any {
  return function asyncWrappedMiddleware(
    req: Request,
    res: Response,
    next: NextFunction
  ) {
    const returnValue = fn(req, res, next)

    if (
      returnValue &&
      returnValue.catch &&
      typeof returnValue.catch === 'function'
    ) {
      return returnValue.catch((err: any) => {
        next(err)
        throw err // <-- Does this need to be here?
      })
    } else {
      return returnValue
    }
  }
}
```

Looking at `express-promise-router`, they don't re-throw in this situation:
```javascript
// Call the route
var ret = handler.apply(null, args);

// If it doesn't return a promise, we exit.
if (!isPromise(ret)) {
    return;
}

// Since we got a promise, we handle calling next
Promise.resolve(ret).then(
    function(d) {
        if (d === 'next') {
            next();
        } else if (d === 'route') {
            next('route');
        }
    },
    function(err) {
        if (!err) {
            err = new Error('returned promise was rejected but did not have a reason');
        }
        next(err); // <-- no rethrow
    }
);
```

Maybe I'm not using the library correctly?

**Comment by jeffijoe** [comment]
I think you're right, it shouldn't rethrow it.

**Comment by jeffijoe** [comment]
@sbarry157 released as 3.0.0, I also bumped the supported node version range.

**Comment by sbarry157** [comment]
@jeffijoe excellent. Thanks for the quick resolution :)

**Comment by jeffijoe** [comment]
No problem! I'd suggest using Koa though. :)
