### ISSUE TITLE
More descriptive error messages when controller method attempting to be invoked does not exist

### ISSUE THREAD

**Issue by jhoscar1** [talyssonoc/awilix-express#9]
Spent some time finding and fixing a bug related to the message `Cannot read property 'apply' of undefined` in the invokers.

Turns out this was coming from the fact that I was attempting to invoke a method that no longer existed because I had changed the name. 

I believe a more descriptive error could be helpful.

**Comment by talyssonoc** [comment]
Thanks for your contribution! Just published v1.1.0 https://www.npmjs.com/package/awilix-express/v/1.1.0
